### ISSUE TITLE
Add code-coverage checks

### ISSUE THREAD

**Issue by hreiche** [Nikhil1912/CSC510-HW_37#39]

**Comment by abidnazirisami** [comment]
I was able to get the codecov working and tested the badge on my fork. The repo owner (Nikhil) needs to update the readme.md with the badge link.

To get the badge, 
- Visit https://app.codecov.io/github/Nikhil1912/CSC510-HW_37
- Go to the settings tab
- Go to Badges & Graphs
- Copy the markdown portion and paste it onto our readme
